kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtaksstotte
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  leaderElection: true
  ingresses:
    - https://veilarbvedtaksstotte-gcp.intern.nav.no
  prometheus:
    enabled: true
    path: veilarbvedtaksstotte/internal/prometheus
  readiness:
    path: veilarbvedtaksstotte/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarbvedtaksstotte/internal/health/liveness
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-2-20480
        databases:
          - name: veilarbvedtaksstotte
            envVarPrefix: DB
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: AIA_BACKEND_URL
      value: https://www.nav.no/aia-backend
    - name: NORG2_URL
      value: https://norg2.intern.nav.no
    - name: POAO_TILGANG_TOKEN_SCOPE
      value: "api://prod-gcp.poao.poao-tilgang/.default"
    - name: POAO_TILGANG_URL
      value: "http://poao-tilgang.poao"
    - name: SAF_URL
      value: "https://saf.intern.nav.no"
    - name: SAF_TOKEN_SCOPE
      value: "api://prod-fss.teamdokumenthandtering.saf/.default"
    - name: VEILARBOPPFOLGING_TOKEN_SCOPE
      value: "api://prod-fss.pto.veilarboppfolging/.default"
    - name: VEILARBOPPFOLGING_URL
      value: "https://veilarboppfolging.prod-fss-pub.nais.io/veilarboppfolging"
    - name: VEILARBVEILEDER_TOKEN_SCOPE
      value: "api://prod-fss.pto.veilarbveileder/.default"
    - name: VEILARBVEILEDER_URL
      value: "https://veilarbveileder.prod-fss-pub.nais.io/veilarbveileder"
    # Topics
    - name: ENDRING_PA_OPPFOLGINGSBRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: ARENA_VEDTAK_TOPIC
      value: teamarenanais.aapen-arena-14avedtakiverksatt-v1-p
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
        - application: veilarbportefolje
          namespace: obo
          permissions:
            roles:
              - "siste-14a-vedtak"
        - application: veilarbpersonflate
          namespace: poao
        - application: beslutteroversikt
          namespace: obo
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
        - application: pto-admin
          namespace: pto
          cluster: prod-fss
        - application: aia-backend
          namespace: paw
        - application: amt-person-service
          namespace: amt
          permissions:
            roles:
              - "siste-14a-vedtak"
    outbound:
      rules:
        - application: aia-backend
          namespace: paw
        - application: paw-arbeidssoker-besvarelse
          namespace: paw
        - application: pto-pdfgen
          namespace: obo
      external:
        - host: team-obo-unleash-api.nav.cloud.nais.io
        - host: www.nav.no
        - host: pdl-api.prod-fss-pub.nais.io
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: veilarbveileder.prod-fss-pub.nais.io
        - host: veilarbarena.prod-fss-pub.nais.io
        - host: saf.prod-fss-pub.nais.io
  envFrom:
    - secret: veilarbvedtaksstotte-unleash-api-token
