kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtaksstotte
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  leaderElection: true
  ingresses:
    - https://veilarbvedtaksstotte.intern.dev.nav.no
  prometheus:
    enabled: true
    path: veilarbvedtaksstotte/internal/prometheus
  readiness:
    path: veilarbvedtaksstotte/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarbvedtaksstotte/internal/health/liveness
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-f1-micro
        databases:
          - name: veilarbvedtaksstotte
            envVarPrefix: DB
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: AIA_BACKEND_URL
      value: https://www.intern.dev.nav.no/aia-backend
    - name: ARENA_VEDTAK_TOPIC
      value: teamarenanais.aapen-arena-14avedtakiverksatt-v1-q1
    - name: DOKUMENTARKIV_URL
      value: https://dokarkiv-q1.dev-fss-pub.nais.io
    - name: ENDRING_PA_OPPFOLGINGS_BRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: NORG2_URL
      value: https://norg2.intern.nav.no
    - name: POAO_TILGANG_TOKEN_SCOPE
      value: "api://dev-gcp.poao.poao-tilgang/.default"
    - name: POAO_TILGANG_URL
      value: "http://poao-tilgang.poao"
    - name: SAF_TOKEN_SCOPE
      value: "api://dev-fss.teamdokumenthandtering.saf/.default"
    - name: SAF_URL
      value: "https://saf-q1.dev.intern.nav.no"
    - name: VEILARBOPPFOLGING_TOKEN_SCOPE
      value: "api://dev-fss.pto.veilarboppfolging/.default"
    - name: VEILARBOPPFOLGING_URL
      value: "https://veilarboppfolging.dev-fss-pub.nais.io/veilarboppfolging"
    - name: VEILARBPERSON_URL
      value: "http://veilarbperson.obo"
    - name: VEILARBVEILEDER_TOKEN_SCOPE
      value: "api://dev-fss.pto.veilarbveileder/.default"
    - name: VEILARBVEILEDER_URL
      value: "https://veilarbveileder.dev-fss-pub.nais.io/veilarbveileder"
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
        - application: veilarbportefolje
          namespace: obo
          permissions:
            roles:
              - "siste-14a-vedtak"
        - application: veilarbpersonflate
          namespace: poao
        - application: beslutteroversikt
          namespace: obo
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
        - application: pto-admin
          namespace: pto
          cluster: dev-fss
        - application: azure-token-generator
          namespace: aura
        - application: amt-person-service
          namespace: amt
          permissions:
            roles:
              - "siste-14a-vedtak"
        - application: pto-pdfgen
          namespace: obo
    outbound:
      rules:
        - application: aia-backend
          namespace: paw
        - application: pdl-api
          namespace: pdl
          cluster: dev-fss
        - application: poao-tilgang
          namespace: poao
        - application: dokarkiv-q1
          namespace: teamdokumenthandtering
          cluster: dev-fss
        - application: regoppslag-q1
          namespace: teamdokumenthandtering
          cluster: dev-fss
        - application: veilarbperson
      external:
        - host: dokarkiv.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
#        - host: regoppslag.dev-fss-pub.nais.io
        - host: saf.dev-fss-pub.nais.io
        - host: saf.dev-fss-pub.nais.io
        - host: team-obo-unleash-api.nav.cloud.nais.io
        - host: veilarbarena.dev-fss-pub.nais.io
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: veilarbveileder.dev-fss-pub.nais.io
  envFrom:
    - secret: veilarbvedtaksstotte-unleash-api-token
