apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: veilarbvedtaksstotte
  namespace: obo
  labels:
    team: obo
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-obo
  secretName: veilarbvedtaksstotte-unleash-api-token
  environment: development
