package org.openapitools.model

import java.util.Locale
import java.util.Objects
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import com.fasterxml.jackson.annotation.JsonValue
import org.openapitools.model.Annet
import org.openapitools.model.BekreftelsStatus
import org.openapitools.model.Bekreftelse
import org.openapitools.model.Bekreftelsesloesning
import org.openapitools.model.Bruker
import org.openapitools.model.Egenvurdering
import org.openapitools.model.Helse
import org.openapitools.model.Jobbsituasjon
import org.openapitools.model.Metadata
import org.openapitools.model.OpplysningerOmArbeidssoeker
import org.openapitools.model.PaaVegneAvStart
import org.openapitools.model.PaaVegneAvStopp
import org.openapitools.model.PeriodeAvluttet
import org.openapitools.model.PeriodeStartet
import org.openapitools.model.Profilering
import org.openapitools.model.ProfilertTil
import org.openapitools.model.Svar
import org.openapitools.model.TidspunktFraKilde
import org.openapitools.model.Utdanning

/**
 * 
 * @param type 
 * @param tidspunkt Tidspunkt for endringen
 * @param utfoertAv 
 * @param kilde Navn på systemet som utførte endringen eller ble benyttet til å utføre endringen
 * @param aarsak Aarasek til endringen. Feks \"Flyttet ut av landet\" eller lignende
 * @param id Unik id for meldingen. Duplikater sees på som nettverkshikke eller lignende og skal trygt kunne ignoreres
 * @param sendtInnAv 
 * @param opplysningerOmArbeidssokerId Unik id for OpplysningerOmArbeidssøker som profileringen tilhører
 * @param profilertTil 
 * @param jobbetSammenhengendeSeksAvTolvSisteMnd Om personen har jobbet sammenhengende seks av de siste tolv månedene
 * @param profileringId Profilering id
 * @param egenvurdering 
 * @param bekreftelsesloesning 
 * @param status 
 * @param svar 
 * @param periodeId UUID for perioden som meldingen gjelder, hentes fra Periode topic eller oppslags api
 * @param intervalMS Interval for bekreftelse i millisekunder. Denne gir registeret et hint om hvor ofte løsningen vil sende meldinger, registeret vil ikke gjøre noe når fristen utløper. 
 * @param graceMS Grace periode i millisekunder. Hvor lenge den som sender bekreftelse på vegne av arbeidssøker venter etter at intervallet er utløpt før den terminerer sine tjenester og stopper bekreftelse på vegne av arbeidssøker. Feks før dagpengene stoppes og og dagpengeløsningen stopper bekreftelse på vegne av arbeidssøker. Dette brukes av registeret for å å kunne oppdage 'døde' klienter, men har ingen funksjonell betydning. 
 * @param tidspunktFraKilde 
 * @param utdanning 
 * @param helse 
 * @param jobbsituasjon 
 * @param annet 
 * @param alder Personens alder
 * @param fristBrutt Angir om grunnen til stopp meldingen er at brukeren har brutt fristen i det eksterne systemet. Dersom denne er satt til true og fristene som ble meldt inn i start meldingen er like eller lenger enn registerets egne frister vil arbeidssøkerperioden bli stoppet umidelbart. 
 */
@JsonIgnoreProperties(
  value = ["type"], // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = Bekreftelse::class, name = "BEKREFTELSE_V1"),
      JsonSubTypes.Type(value = Egenvurdering::class, name = "EGENVURDERING_V1"),
      JsonSubTypes.Type(value = OpplysningerOmArbeidssoeker::class, name = "OPPLYSNINGER_V4"),
      JsonSubTypes.Type(value = PaaVegneAvStart::class, name = "PAA_VEGNE_AV_START_V1"),
      JsonSubTypes.Type(value = PaaVegneAvStopp::class, name = "PAA_VEGNE_AV_STOPP_V1"),
      JsonSubTypes.Type(value = PeriodeAvluttet::class, name = "PERIODE_AVSLUTTET_V1"),
      JsonSubTypes.Type(value = PeriodeStartet::class, name = "PERIODE_STARTET_V1"),
      JsonSubTypes.Type(value = Profilering::class, name = "PROFILERING_V1")
)

interface Hendelse {
        
        val type: Hendelse.Type

        
        val tidspunkt: java.time.OffsetDateTime

        
        val utfoertAv: Bruker

        
        val kilde: kotlin.String

        
        val aarsak: kotlin.String

        
        val id: java.util.UUID

        
        val sendtInnAv: Metadata

        
        val opplysningerOmArbeidssokerId: java.util.UUID

        
        val profilertTil: ProfilertTil

        
        val jobbetSammenhengendeSeksAvTolvSisteMnd: kotlin.Boolean

        
        val profileringId: java.util.UUID

        
        val egenvurdering: ProfilertTil

        
        val bekreftelsesloesning: Bekreftelsesloesning

        
        val status: BekreftelsStatus

        
        val svar: Svar

        
        val periodeId: java.util.UUID

        
        val intervalMS: kotlin.Long

        
        val graceMS: kotlin.Long

        
        val tidspunktFraKilde: TidspunktFraKilde? 

        
        val utdanning: Utdanning? 

        
        val helse: Helse? 

        
        val jobbsituasjon: Jobbsituasjon? 

        
        val annet: Annet? 

        
        val alder: kotlin.Int? 

        
        val fristBrutt: kotlin.Boolean? 


    /**
    * 
    * Values: PERIODE_STARTET_V1,PERIODE_AVSLUTTET_V1,OPPLYSNINGER_V4,PROFILERING_V1,EGENVURDERING_V1,BEKREFTELSE_V1,PAA_VEGNE_AV_START_V1,PAA_VEGNE_AV_STOPP_V1
    */
    enum class Type(@get:JsonValue val value: kotlin.String) {

        PERIODE_STARTET_V1("PERIODE_STARTET_V1"),
        PERIODE_AVSLUTTET_V1("PERIODE_AVSLUTTET_V1"),
        OPPLYSNINGER_V4("OPPLYSNINGER_V4"),
        PROFILERING_V1("PROFILERING_V1"),
        EGENVURDERING_V1("EGENVURDERING_V1"),
        BEKREFTELSE_V1("BEKREFTELSE_V1"),
        PAA_VEGNE_AV_START_V1("PAA_VEGNE_AV_START_V1"),
        PAA_VEGNE_AV_STOPP_V1("PAA_VEGNE_AV_STOPP_V1");

        companion object {
            @JvmStatic
            @JsonCreator
            fun forValue(value: kotlin.String): Type {
                return values().firstOrNull{it -> it.value == value}
                    ?: throw IllegalArgumentException("Unexpected value '$value' for enum 'Hendelse'")
            }
        }
    }

}

