package org.openapitools.model

import java.util.Locale
import java.util.Objects
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import com.fasterxml.jackson.annotation.JsonValue
import org.openapitools.model.IdentitetsnummerQueryRequest
import org.openapitools.model.PerioderQueryRequest

/**
 * 
 * @param type 
 * @param perioder 
 * @param identitetsnummer Norsk identitetsnummer (11 siffer, ingen andre tegn)
 */
@JsonIgnoreProperties(
  value = ["type"], // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = IdentitetsnummerQueryRequest::class, name = "IDENTITETSNUMMER"),
      JsonSubTypes.Type(value = PerioderQueryRequest::class, name = "PERIODER")
)

interface QueryRequest {
        
        val type: QueryRequest.Type

        
        val perioder: kotlin.collections.List<java.util.UUID>

        
        val identitetsnummer: kotlin.String


    /**
    * 
    * Values: PERIODER,IDENTITETSNUMMER
    */
    enum class Type(@get:JsonValue val value: kotlin.String) {

        PERIODER("PERIODER"),
        IDENTITETSNUMMER("IDENTITETSNUMMER");

        companion object {
            @JvmStatic
            @JsonCreator
            fun forValue(value: kotlin.String): Type {
                return values().firstOrNull{it -> it.value == value}
                    ?: throw IllegalArgumentException("Unexpected value '$value' for enum 'QueryRequest'")
            }
        }
    }

}

