# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbvedtaksstotte
team: biff
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
leaderElection: true
healthcheck:
  liveness:
    path: veilarbvedtaksstotte/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbvedtaksstotte/internal/isReady
    initialDelay: 20
prometheus:
  enabled: true
  path: veilarbvedtaksstotte/internal/metrics
resources:
  limits:
    cpu: 3
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
fasitResources:
  used:
  - alias: veilarbvedtaksstotteDB
    resourceType: datasource
  - alias: loadbalancer:veilarbvedtaksstotte
    resourceType: loadbalancerconfig
  - alias: srvveilarbvedtaksstotte
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  - alias: kafka-brokers
    resourceType: baseurl
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: abac.pdp.endpoint
    resourceType: restservice
  - alias: saf.hentdokument
    resourceType: restservice
    propertyMap:
      url: SAF_HENTDOKUMENT_URL

  # ISSO
  - alias: isso-host
    resourceType: baseurl
  - alias: isso-jwks
    resourceType: baseurl
  - alias: isso-issuer
    resourceType: baseurl
  - alias: isso.isalive
    resourceType: baseurl
  - alias: isso-rp-user
    resourceType: credential
  - alias: veilarblogin.redirect-url
    resourceType: restservice
    propertyMap:
      url: OIDC_REDIRECT_URL

  exposed:
  - alias: veilarbvedtaksstotteAPI
    resourceType: restservice
    path: /veilarbvedtaksstotte/api

alertProfiles:
  - common-java-modules
