version: '3.3'
services:
  db:
    image: postgres:11-alpine
    container_name: veilarbvedtaksstotte-postgres
    volumes:
      - veilarbvedtaksstotte-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: veilarbvedtaksstotte

volumes:
  veilarbvedtaksstotte-db-volume: