version: '3.3'
services:
  db:
    image: postgres:11-alpine
    container_name: veilarbvedtaksstotte-postgres
    volumes:
      - veilarbvedtaksstotte-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: veilarbvedtaksstotte
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        aapen-oppfolging-vedtakSendt-v1-q0:1:1
        aapen-oppfolging-vedtakStatusEndring-v1-q0:1:1
        aapen-fo-endringPaaAvsluttOppfolging-v1-q0:1:1
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

volumes:
  veilarbvedtaksstotte-db-volume: