kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtaksstotte
  namespace: default
  labels:
    team: pto
  cluster: prod-fss
spec:
  image: docker.pkg.github.com/navikt/veilarbvedtaksstotte/veilarbvedtaksstotte:{{version}}
  port: 8080
  webproxy: true
  leaderElection: true
  ingresses:
    - https://app.adeo.no/veilarbvedtaksstotte
    - https://veilarbvedtaksstotte.nais.adeo.no
  prometheus:
    enabled: true
    path: veilarbvedtaksstotte/internal/prometheus
  readiness:
    path: veilarbvedtaksstotte/internal/isReady
    initialDelay: 30
  liveness:
    path: veilarbvedtaksstotte/internal/isAlive
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbvedtaksstotte
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbvedtaksstotte/default
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
