kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtaksstotte
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbvedtaksstotte/veilarbvedtaksstotte:{{version}}
  port: 8080
  webproxy: true
  leaderElection: true
  ingresses:
    - https://veilarbvedtaksstotte.dev-fss-pub.nais.io
    - https://app.dev.adeo.no/veilarbvedtaksstotte
    - https://app-q1.dev.adeo.no/veilarbvedtaksstotte
    - https://app-q1.adeo.no/veilarbvedtaksstotte
    - https://veilarbvedtaksstotte-q1.nais.preprod.local
  prometheus:
    enabled: true
    path: veilarbvedtaksstotte/internal/prometheus
  readiness:
    path: veilarbvedtaksstotte/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarbvedtaksstotte/internal/health/liveness
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbvedtaksstotte
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarbvedtaksstotte/q1
        mountPath: /var/run/secrets/nais.io/vault
  kafka:
    pool: nav-dev
  env:
    - name: ENDRING_PA_AVSLUTT_OPPFOLGING_TOPIC
      value: aapen-fo-endringPaaAvsluttOppfolging-v1-q1
    - name: ENDRING_PA_OPPFOLGINGS_BRUKER_TOPIC
      value: aapen-fo-endringPaaOppfoelgingsBruker-v1-q1
    - name: VEDTAK_SENDT_TOPIC
      value: aapen-oppfolging-vedtakSendt-v1-q1
    - name: ARENA_VEDTAK_TOPIC
      value: aapen-arena-14aVedtakIverksatt-v1-q1
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: dev-fss
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: dev-gcp
  envFrom:
    - configmap: pto-config
