version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.40
workflows:
  version: 2
  commit:
    jobs:
      - pus/test-backend:
          context: pus
          filters:
            branches:
              ignore:
                - master
                - dev
      - pus/bygg-og-deploy-backend:
          context: pus
          filepath: nais-q.yaml
          filters:
            branches:
              only: kaizen-0-naiserator
      - pus/bygg-og-deploy-backend:
          context: pus
          filepath: nais.yaml
          filters:
            branches:
              only: master
