name: Test, build, push and deploy
on: push
env:
  IMAGE_TAG: ${{ github.sha }}
  PRINT_PAYLOAD: true
permissions:
  packages: write
  contents: write
  id-token: write
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Run maven tests
        run: mvn -B verify

  test-build-and-push:
    name: Test, build and push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/gcp-migration'
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build maven artifacts
        run: mvn -B package

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: obo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy application to dev-gcp
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/gcp-migration'
    needs: test-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/application/gcp/application-config-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release to dev-gcp
          tag_name: release/dev@${{ env.IMAGE_TAG }}
          prerelease: true

  deploy-prod:
    name: Deploy application to prod-gcp
    if: github.ref == 'refs/heads/master-gcp'
    needs: test-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/application/gcp/application-config-prod.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release to prod
          tag_name: release/prod@${{ env.IMAGE_TAG }}
          prerelease: false
