
DROP TABLE VEDTAK_STATUS_ENDRING_KAFKA_FEIL;
DROP TABLE VEDTAK_SENDT_KAFKA_FEIL;

CREATE TYPE KAFKA_TOPIC_TYPE AS enum (
    'VEDTAK_SENDT',
    'VEDTAK_STATUS_ENDRING'
);

CREATE TABLE FEILET_KAFKA_MELDING (
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    TOPIC                   KAFKA_TOPIC_TYPE NOT NULL,
    KEY                     VARCHAR(40) NOT NULL,
    PAYLOAD                 JSON NOT NULL
);
