
CREATE TYPE BESLUTTER_OVERSIKT_STATUS_TYPE AS enum (
    'TRENGER_BESLUTTER',
    'HAR_BESLUTTER',
    'KLAR_TIL_BESLUTTER',
    'KLAR_TIL_VEILEDER',
    'GODKJENT_AV_BESLUTTER'
);

CREATE TABLE BESLUTTEROVERSIKT_BRUKER (
    ID                              BIGSERIAL PRIMARY KEY NOT NULL,
    VEDTAK_ID                       BIGSERIAL NOT NULL,
    BRUKER_FORNAVN                  VARCHAR(100) NOT NULL,
    BRUKER_ETTERNAVN                VARCHAR(100) NOT NULL,
    BRUKER_OPPFOLGINGSENHET_NAVN    VARCHAR(100) NOT NULL,
    BRUKER_FNR                      VARCHAR(20) NOT NULL,
    VEDTAK_STARTET                  TIMESTAMP NOT NULL,
    STATUS                          BESLUTTER_OVERSIKT_STATUS_TYPE NOT NULL,
    BESLUTTER_NAVN                  VARCHAR(100),
    VEILEDER_NAVN                   VARCHAR(100) NOT NULL,
    FOREIGN KEY (VEDTAK_ID) REFERENCES VEDTAK(ID)
);