CREATE TABLE SYSTEM_MELDING (
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    VEDTAK_ID               BIGINT NOT NULL,
    TYPE                    SYSTEM_MELDING_TYPE, NOT NULL,
    OPPRETTET               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UTFORT_AV_NAVN          VARCHAR(200),
    FOREIGN KEY (VEDTAK_ID) REFERENCES VEDTAK(ID)
);