CREATE TYPE SYSTEM_MELDING_TYPE AS enum (
    'UTKAST_OPPRETTET',
    'BESLUTTER_PROSESS_STARTET',
    'BLITT_BESLUTTER',
    'BESLUTTER_HAR_GODKJENT',
    'TATT_OVER_SOM_BESLUTTER',
    'TATT_OVER_SOM_VEILEDER'
);

CREATE TABLE SYSTEM_MELDING (
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    VEDTAK_ID               BIGINT NOT NULL,
    SYSTEM_MELDING_TYPE     SYSTEM_MELDING_TYPE NOT NULL,
    OPPRETTET               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UTFORT_AV_IDENT         VARCHAR(200),
    FOREIGN KEY (VEDTAK_ID) REFERENCES VEDTAK(ID)
);