CREATE SEQUENCE VEDTAK_UTKAST_SEQ;

CREATE TABLE VEDTAK_UTKAST (
  VEDTAK_UTKAST_ID        NUMBER,
  AKTOR_ID                VARCHAR(20) NOT NULL,
  VEKTLAGT_OPPLYSNINGER   CLOB,
  VEILEDER_IDENT          VARCHAR(10) NOT NULL,
  VEILEDER_ENHET_ID       VARCHAR(4) NOT NULL,
  SIST_OPPDATERT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  BEGRUNNELSE             CLOB
);

CREATE INDEX VEDTAK_UTKAST_AKTOR_ID_INDEX ON VEDTAK_UTKAST ("AKTOR_ID");
