CREATE TABLE VEDTAK (
  VEDTAK_ID               NUMBER NOT NULL,
  AKTOR_ID                VARCHAR(20) NOT NULL,
  HOVEDMAL                varchar(30),
  INNSATSGRUPPE           varchar(40),
  VEILEDER_IDENT          VARCHAR(20) NOT NULL,
  VEILEDER_ENHET_ID       VARCHAR(4) NOT NULL,
  SIST_OPPDATERT          TIMESTAMP NOT NULL,
  SENDT                   TIMESTAMP,
  BEGRUNNELSE             CLOB,
  STATUS                  varchar(10) NOT NULL,
  CONSTRAINT "VEDTAK_PK" PRIMARY KEY ("VEDTAK_ID")
);

CREATE INDEX VEDTAK_AKTOR_ID_INDEX ON VEDTAK ("AKTOR_ID");
