CREATE SEQUENCE VEDTAK_SEQ;

CREATE TABLE VEDTAK (
  VEDTAK_ID               NUMBER,
  AKTOR_ID                VARCHAR(20) NOT NULL,
  VEKTLAGT_OPPLYSNINGER   CLOB,
  HOVEDMAL_TYPE           varchar(30),
  KONKLUSJON_TYPE         varchar(40),
  VEILEDER_IDENT          VARCHAR(20) NOT NULL,
  VEILEDER_ENHET_ID       VARCHAR(4) NOT NULL,
  SIST_OPPDATERT          TIMESTAMP NOT NULL,
  BEGRUNNELSE             CLOB,
  STATUS                  varchar(10),
  CONSTRAINT "VEDTAK_PK" PRIMARY KEY ("VEDTAK_ID")
);

CREATE INDEX VEDTAK_AKTOR_ID_INDEX ON VEDTAK ("AKTOR_ID");
