CREATE SEQUENCE VEDTAK_SENDT_SEQ;

CREATE TABLE VEDTAK_SENDT_KAFKA_FEIL (
  VEDTAK_SENDT_ID         NUMBER NOT NULL,
  VEDTAK_SENDT            TIMESTAMP NOT NULL,
  INNSATSGRUPPE           VARCHAR(40) NOT NULL,
  AKTOR_ID                VARCHAR(20) NOT NULL,
  CONSTRAINT "VEDTAK_SENDT_PK" PRIMARY KEY ("VEDTAK_SENDT_ID")
);
