CREATE TABLE KILDE_TYPE (
  VERDI                   VARCHAR(20) NOT NULL
);

INSERT INTO KILDE_TYPE (VERDI) VALUES ('PAM_CV_API');
INSERT INTO KILDE_TYPE (VERDI) VALUES ('JOBBPROFIL');
INSERT INTO KILDE_TYPE (VERDI) VALUES ('REGISTRERINGSINFO');
INSERT INTO KILDE_TYPE (VERDI) VALUES ('VEILARBVEDTAKINFO');

-- TODO: Trenger vi KILDE_TYPE?


CREATE SEQUENCE OPPLYSNING_SEQ;

CREATE TABLE OPPLYSNING (
  OPPLYSNING_ID           NUMBER NOT NULL,
  VEDTAK_ID               NUMBER NOT NULL,
  KILDE                   VARCHAR(20),
  JSON                    BLOB,
  CONSTRAINT "OPPLYSNING_PK" PRIMARY KEY ("OPPLYSNING_ID"),
  CONSTRAINT ensure_json CHECK (JSON IS JSON)
);




CREATE SEQUENCE ANDRE_OPPLYSNINGER_SEQ;

CREATE TABLE ANDRE_OPPLYSNINGER (
  ANDRE_OPPLYSNINGER_ID   NUMBER NOT NULL,
  VEDTAK_ID               NUMBER NOT NULL,
  TEKST                   VARCHAR(500),
  CONSTRAINT "ANDRE_OPPLYSNINGER_PK" PRIMARY KEY ("ANDRE_OPPLYSNINGER_ID")
);