CREATE TABLE KILDE_TYPE (
  VERDI                   VARCHAR(20) NOT NULL
);

INSERT INTO KILDE_TYPE (VERDI) VALUES ('PAM_CV_API');
INSERT INTO KILDE_TYPE (VERDI) VALUES ('JOBBPROFIL');
INSERT INTO KILDE_TYPE (VERDI) VALUES ('REGISTRERINGSINFO');
INSERT INTO KILDE_TYPE (VERDI) VALUES ('VEILARBVEDTAKINFO');

-- TODO: Trenger vi KILDE_TYPE?


CREATE SEQUENCE OPPLYSNING_SEQ;

CREATE TABLE OPPLYSNING (
  VEDTAK_ID               NUMBER NOT NULL,
  VALGT                   NUMBER(1) NOT NULL,
  KILDE                   VARCHAR(20),
  JSON                    BLOB,
  CONSTRAINT ensure_json CHECK (JSON IS JSON),
  CONSTRAINT KILDE_TYPE_FK FOREIGN KEY (KILDE) REFERENCES KILDE_TYPE (VERDI)
);




CREATE SEQUENCE ANDRE_OPPLYSNINGER_SEQ;

CREATE TABLE ANDRE_OPPLYSNINGER (
  VEDTAK_ID               NUMBER NOT NULL,
  TEKST                   VARCHAR(500)
);