CREATE TABLE KILDE_TYPE (
  VERDI                   VARCHAR(20) NOT NULL
);

INSERT INTO KILDE_TYPE (VERDI) VALUES ('CV_OG_JOBBPROFIL');
INSERT INTO KILDE_TYPE (VERDI) VALUES ('REGISTRERINGSINFO');
INSERT INTO KILDE_TYPE (VERDI) VALUES ('VEILARBVEDTAKINFO');

CREATE TABLE OYBLIKKSBILDE (
  VEDTAK_ID               NUMBER NOT NULL,
  KILDE                   VARCHAR(20),
  JSON                    BLOB,
  CONSTRAINT ensure_json CHECK (JSON IS JSON),
  CONSTRAINT KILDE_TYPE_FK FOREIGN KEY (KILDE) REFERENCES KILDE_TYPE (VERDI)
);

CREATE TABLE OPPLYSNING (
  VEDTAK_ID               NUMBER NOT NULL,
  TEKST                   VARCHAR(500)
);
