ALTER TABLE VEDTAK ADD UTKAST_OPPRETTET TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE VEDTAK SET UTKAST_OPPRETTET = SIST_OPPDATERT WHERE UTKAST_OPPRETTET IS NULL;

ALTER TABLE VEDTAK MODIFY UTKAST_OPPRETTET NOT NULL;
