
CREATE TYPE KAFKA_MESSAGE_TYPE AS enum ('PRODUCED','CONSUMED');

ALTER TABLE FEILET_KAFKA_MELDING ALTER COLUMN TOPIC TYPE VARCHAR(100);

ALTER TABLE FEILET_KAFKA_MELDING ADD COLUMN MESSAGE_TYPE KAFKA_MESSAGE_TYPE NOT NULL;

ALTER TABLE FEILET_KAFKA_MELDING ADD COLUMN MESSAGE_OFFSET BIGINT;

ALTER TABLE FEILET_KAFKA_MELDING ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

DROP TYPE KAFKA_TOPIC_TYPE;

