ALTER TABLE vedtak
    RENAME COLUMN SIST_OPPDATERT TO UTKAST_SIST_OPPDATERT;

ALTER TABLE vedtak
    ADD COLUMN VEDTAK_FATTET TIMESTAMP DEFAULT NULL;

UPDATE vedtak
    SET VEDTAK_FATTET = UTKAST_SIST_OPPDATERT
    WHERE STATUS = 'SENDT';