CREATE TABLE TILGANGSKONTROLL_ENHET (
    ENHET_ID                        VARCHAR(4) NOT NULL,
    CREATED_AT                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE(ENHET_ID)
);

CREATE INDEX TILGANGSKONTROLL_ENHET_ENHET_ID_IDX ON TILGANGSKONTROLL_ENHET(ENHET_ID);
