ALTER TABLE KAFKA_CONSUMER_RECORD ALTER COLUMN KEY      DROP NOT NULL;
ALTER TABLE KAFKA_CONSUMER_RECORD ALTER COLUMN VALUE    DROP NOT NULL;
ALTER TABLE KAFKA_PRODUCER_RECORD ALTER COLUMN KEY      DROP NOT NULL;
ALTER TABLE KAFKA_PRODUCER_RECORD ALTER COLUMN VALUE    DROP NOT NULL;
