CREATE SEQUENCE SAK_STATISTIKK_ID_SEQ;

CREATE TABLE SAK_STATISTIKK
(
    BEHANDLING_UUID         VARCHAR(36)  NOT NULL PRIMARY KEY,
    BEHANDLING_ID           VARCHAR(30)  NOT NULL,
    RELATERT_BEHANDLING_ID  VARCHAR(30),
    SAK_ID                  VARCHAR(30),
    AKTOR_ID                VARCHAR(20)  NOT NULL,
    MOTTATT_TID             TIMESTAMP  NOT NULL,
    REGISTRERT_TID          TIMESTAMP  NOT NULL,
    FERDIGBEHANDLET_TID     TIMESTAMP  NOT NULL,
    TEKNISK_TID             TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SOKNADSFORMAT           VARCHAR(10),
    SAK_YTELSE              VARCHAR(50),
    BEHANDLING_TYPE         VARCHAR(30),
    BEHANDLING_STATUS       VARCHAR(30),
    BEHANDLING_RESULTAT     VARCHAR(50),
    BEHANDLING_METODE       VARCHAR(30),
    OPPRETTET_AV            VARCHAR(10) NOT NULL,
    SAKSBEHANDLER           VARCHAR(10),
    ANSVARLIG_BESLUTTER     VARCHAR(10),
    ANSVARLIG_ENHET         VARCHAR(10),
    AVSENDER                VARCHAR(50),
    VERSJON                 VARCHAR(100)
);

