CREATE TABLE OPPFOLGINGSPERIODE(
    OPPFOLGINGSPERIODE_ID UUID PRIMARY KEY,
    AKTORID VARCHAR(20) NOT NULL,
    STARTDATO TIMESTAMP WITH TIME ZONE NOT NULL,
    SLUTTDATO TIMESTAMP WITH TIME ZONE,
    STARTET_BEGRUNNELSE VARCHAR(100)
);

CREATE INDEX OPPFOLGINGSPERIODE_AKTORID_IDX ON OPPFOLGINGSPERIODE(AKTORID);
