CREATE TABLE SISTE_OPPFOLGING_PERIODE(
    OPPFOLGINGSPERIODE_ID UUID PRIMARY KEY,
    AKTORID VARCHAR(20) NOT NULL,
    STARTDATO TIMESTAMP WITH TIME ZONE NOT NULL,
    SLUTTDATO TIMESTAMP WITH TIME ZONE
);

CREATE INDEX SISTE_OPPFOLGINGSPERIODE_IDX ON SISTE_OPPFOLGING_PERIODE(AKTORID);