
CREATE TYPE KAFKA_VEDTAK_STATUS_TYPE AS enum (
    'UTKAST_OPPRETTET',
    'SENDT_TIL_BESLUTTER',
    'SENDT_TIL_BRUKER'
    );

CREATE TABLE VEDTAK_STATUS_ENDRING_KAFKA_FEIL (
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    AKTOR_ID                VARCHAR(20) NOT NULL,
    HOVEDMAL                VARCHAR(30),
    INNSATSGRUPPE           VARCHAR(40),
    SIST_REDIGERT_TIDSPUNKT TIMESTAMP NOT NULL,
    STATUS_ENDRET_TIDSPUNKT TIMESTAMP NOT NULL,
    KAFKA_VEDTAK_STATUS     KAFKA_VEDTAK_STATUS_TYPE NOT NULL
);
