CREATE INDEX SAK_STATISTIKK_BEHANDLING_ID_IDX ON SAK_STATISTIKK(BEHANDLING_ID);
CREATE INDEX OYEBLIKKSBILDE_VEDTAK_ID_IDX ON OYEBLIKKSBILDE(VEDTAK_ID);
CREATE INDEX VEDTAK_DOKUMENT_BESTILLING_ID_IDX ON VEDTAK(DOKUMENT_BESTILLING_ID);
CREATE INDEX VEDTAK_JOURNALPOST_ID_IDX ON VEDTAK(JOURNALPOST_ID);
