ALTER TABLE RETRY_VEDTAKDISTRIBUSJON
    ADD COLUMN RAD_OPPRETTET TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN SIST_FORSOKT TIMESTAMP DEFAULT CURRENT_TIMESTAMP; -- Rader settes kun inn etter å ha blitt forsøkt distribuert første gang
