CREATE TABLE KLAGE
(
    VEDTAK_ID                       BIGINT PRIMARY KEY,
    VEILEDER_IDENT                  VARCHAR(255) NOT NULL,
    NORSK_IDENT                     VARCHAR(11)  NOT NULL,
    BRUKER_KLAGE_DATO               DATE,
    BRUKER_KLAGE_BEGRUNNELSE        TEXT,
    TIDSPUNKT_START_KLAGEBEHANDLING TIMESTAMP    NOT NULL,
    RAD_SIST_ENDRET                 TIMESTAMP    NOT NULL
);
