DROP TABLE IF EXISTS KLAGE;
CREATE TABLE KLAGE
(
    VEDTAK_ID                       BIGINT PRIMARY KEY,
    VEILEDER_IDENT                  VARCHAR(20) NOT NULL,
    NORSK_IDENT                     VARCHAR(11) NOT NULL,
    TIDSPUNKT_START_KLAGEBEHANDLING TIMESTAMP   NOT NULL,
    KLAGE_DATO                      DATE,
    KLAGE_JOURNALPOST_ID            VARCHAR(20),
    FORMKRAV_OPPFYLT                VARCHAR(20),
    FORMKRAV_BEGRUNNELSE            TEXT,
    RESULTAT                        VARCHAR(30),
    RESULTAT_BEGRUNNELSE            TEXT,
    TIDSPUNKT_RESULTAT              TIMESTAMP,
    RAD_SIST_ENDRET                 TIMESTAMP   NOT NULL
);

