CREATE TABLE KLAGE
(
    VEDTAK_ID                           BIGINT PRIMARY KEY,
    VEILEDER_IDENT                      VARCHAR(20) NOT NULL,
    NORSK_IDENT                         VARCHAR(11) NOT NULL,
    TIDSPUNKT_START_KLAGEBEHANDLING     TIMESTAMP   NOT NULL,
    KLAGE_DATO                          DATE        NOT NULL,
    KLAGE_JOURNALPOST_ID                VARCHAR(20) NOT NULL,
    FORMKRAV_SIGNERT                    VARCHAR(20),
    FORMKRAV_PART                       VARCHAR(20),
    FORMKRAV_KONKRET                    VARCHAR(20),
    FORMKRAV_KLAGEFRIST_OPPRETTHOLDT    VARCHAR(20),
    FORMKRAV_KLAGEFRIST_UNNTAK          VARCHAR(50),
    FORMKRAV_OPPFYLT                    VARCHAR(20) NOT NULL,
    FORMKRAV_BEGRUNNELSE_INTERN         TEXT,
    FORMKRAV_BEGRUNNELSE_BREV           TEXT,
    TIDSPUNKT_FORMKRAV                  TIMESTAMP,
    RESULTAT                            VARCHAR(30) NOT NULL,
    RESULTAT_BEGRUNNELSE                TEXT,
    TIDSPUNKT_RESULTAT                  TIMESTAMP,
    TIDSPUNKT_OVERSENDT_TIL_KABAL       TIMESTAMP,
    STATUS                              VARCHAR(30) NOT NULL,
    BREV_FORMKRAV_AVVIST_JOURNALPOST_ID VARCHAR(20),
    RAD_SIST_ENDRET                     TIMESTAMP   NOT NULL
);


