ALTER TABLE KLAGE
ADD COLUMN KLAGEBEHANDLING_ID UUID;

UPDATE KLAGE
SET KLAGEBEHANDLING_ID = gen_random_uuid()
WHERE KLAGEBEHANDLING_ID IS NULL;

ALTER TABLE KLAGE
ALTER COLUMN KLAGEBEHANDLING_ID SET NOT NULL,
ALTER COLUMN KLAGEBEHANDLING_ID SET DEFAULT gen_random_uuid();