
ALTER TABLE OYBLIKKSBILDE
    RENAME TO OYEBLIKKSBILDE;

ALTER TABLE OYEBLIKKSBILDE
    RENAME COLUMN OYBLIKKSBILDE_TYPE TO OYEBLIKKSBILDE_TYPE;

ALTER TYPE OYBLIKKSBILDE_TYPE
    RENAME TO OYEBLIKKSBILDE_TYPE;
