kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtaksstotte
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  leaderElection: true
  ingresses:
    - https://veilarbvedtaksstotte.prod-fss-pub.nais.io
    - https://veilarbvedtaksstotte.intern.nav.no
    - https://app.adeo.no/veilarbvedtaksstotte
    - https://veilarbvedtaksstotte.nais.adeo.no
  prometheus:
    enabled: true
    path: veilarbvedtaksstotte/internal/prometheus
  readiness:
    path: veilarbvedtaksstotte/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarbvedtaksstotte/internal/health/liveness
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbvedtaksstotte
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbvedtaksstotte/default
        mountPath: /var/run/secrets/nais.io/vault
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: ENDRING_PA_OPPFOLGINGS_BRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: ARENA_VEDTAK_TOPIC
      value: teamarenanais.aapen-arena-14avedtakiverksatt-v1-p
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.nais.local
    - name: POAO_TILGANG_SCOPE
      value: api://prod-fss.poao.poao-tilgang/.default
    - name: AIA_BACKEND_URL
      value: https://www.nav.no/aia-backend
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: veilarbportefolje
          namespace: pto
          cluster: prod-fss
          permissions:
            roles:
              - "siste-14a-vedtak"
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: prod-gcp
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
          cluster: prod-gcp
        - application: pto-admin
          namespace: pto
          cluster: prod-fss
        - application: aia-backend
          namespace: paw
          cluster: prod-gcp
        - application: amt-person-service
          namespace: amt
          cluster: prod-gcp
          permissions:
            roles:
              - "siste-14a-vedtak"
    outbound:
      rules:
        - application: aia-backend
          namespace: paw
          cluster: prod-gcp
        - application: paw-arbeidssoker-besvarelse
          namespace: paw
          cluster: prod-gcp
        - application: pto-pdfgen
          namespace: obo
          cluster: prod-gcp
      external:
        - host: team-obo-unleash-web.nav.cloud.nais.io
        - host: www.nav.no
  envFrom:
    - configmap: pto-config
    - secret: veilarbvedtaksstotte-unleash-api-token
