kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtaksstotte
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  leaderElection: true
  ingresses:
    - https://veilarbvedtaksstotte.intern.nav.no
  prometheus:
    enabled: true
    path: veilarbvedtaksstotte/internal/prometheus
  readiness:
    path: veilarbvedtaksstotte/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarbvedtaksstotte/internal/health/liveness
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-1-6656 # 1 vCPU, 6.5 GiB (6.5*1024 MB) RAM
        databases:
          - name: veilarbvedtaksstotte
            envVarPrefix: DB
            users:
              - name: bigquery_user_prod
    bigQueryDatasets:
      - description: Datasett for statistikk for 14a vedtak
        name: 14a_vedtak_statistikk
        permission: READWRITE
  observability:
    logging:
      destinations:
        - id: elastic
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: AIA_BACKEND_TOKEN_SCOPE
      value: api://prod-gcp.paw.aia-backend/.default
    - name: AIA_BACKEND_URL
      value: http://aia-backend.paw/aia-backend
    - name: DOKARKIV_TOKEN_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io
    - name: DOKDISTFORDELING_URL # bruker saf-scope
      value: https://dokdistfordeling.prod-fss-pub.nais.io
    - name: NORG2_URL
      value: http://norg2.org/norg2
    - name: PDL_TOKEN_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: POAO_TILGANG_TOKEN_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: PTO_PDFGEN_URL
      value: http://pto-pdfgen.obo
    - name: REGOPPSLAG_TOKEN_SCOPE
      value: api://prod-fss.teamdokumenthandtering.regoppslag/.default
    - name: REGOPPSLAG_URL
      value: https://regoppslag.prod-fss-pub.nais.io
    - name: SAF_TOKEN_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: SAF_URL
      value: https://saf.prod-fss-pub.nais.io
    - name: VEILARBARENA_TOKEN_SCOPE
      value: api://prod-fss.pto.veilarbarena/.default
    - name: VEILARBARENA_URL
      value: https://veilarbarena.prod-fss-pub.nais.io/veilarbarena
    - name: VEILARBOPPFOLGING_TOKEN_SCOPE
      value: api://prod-gcp.poao.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.poao/veilarboppfolging
    - name: VEILARBPERSON_TOKEN_SCOPE
      value: api://prod-gcp.obo.veilarbperson/.default
    - name: VEILARBPERSON_URL
      value: http://veilarbperson.obo/veilarbperson
    - name: VEILARBVEILEDER_TOKEN_SCOPE
      value: api://prod-gcp.obo.veilarbveileder/.default
    - name: VEILARBVEILEDER_URL
      value: http://veilarbveileder.obo/veilarbveileder
    # Topics
    - name: ENDRING_PA_OPPFOLGINGSBRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: ARENA_VEDTAK_TOPIC
      value: teamarenanais.aapen-arena-14avedtakiverksatt-v1-p
    # BigQuery
    - name: BQ_DATASET_NAME
      value: 14a_vedtak_statistikk
    - name: BQ_TABLE_NAME
      value: statistikk_dvh_fellestabell
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
        - application: veilarbportefolje
          namespace: obo
          permissions:
            roles:
              - "siste-14a-vedtak"
        - application: veilarbpersonflate
          namespace: poao
        - application: inngar
          namespace: dab
        - application: beslutteroversikt
          namespace: obo
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
        - application: poao-admin
          namespace: poao
          cluster: prod-gcp
        - application: amt-person-service
          namespace: amt
          permissions:
            roles:
              - "gjeldende-14a-vedtak"
              - "siste-14a-vedtak"
        # Lenke til behandling i Behandlingskatalogen: https://behandlingskatalog.intern.nav.no/process/team/7ec4b786-ddf7-4c56-ab2f-3c3edeb0d33f/4ff22ca5-c66a-4127-9271-9de34800c8dd
        - application: modiapersonoversikt-api
          namespace: personoversikt
        # Lenke til behandling i Behandlingskatalogen: https://behandlingskatalog.ansatt.nav.no/process/team/0150fd7c-df30-43ee-944e-b152d74c64d6/780e3168-cf58-46ec-9764-a6cdd3da3b8f
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss
          permissions:
            roles:
              - "gjeldende-14a-vedtak"
    outbound:
      rules:
        - application: aia-backend
          namespace: paw
        - application: pto-pdfgen
          namespace: obo
        - application: veilarboppfolging
          namespace: poao
        - application: veilarbperson
          namespace: obo
        - application: veilarbveileder
          namespace: obo
        - application: poao-tilgang
          namespace: poao
        - application: norg2
          namespace: org
      external:
        - host: team-obo-unleash-api.nav.cloud.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: veilarbarena.prod-fss-pub.nais.io
        - host: saf.prod-fss-pub.nais.io
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: dokdistfordeling.prod-fss-pub.nais.io
        - host: regoppslag.prod-fss-pub.nais.io
  envFrom:
    - secret: veilarbvedtaksstotte-unleash-api-token
