kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtaksstotte
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  leaderElection: true
  ingresses:
    - https://veilarbvedtaksstotte.intern.nav.no
  prometheus:
    enabled: true
    path: veilarbvedtaksstotte/internal/prometheus
  readiness:
    path: veilarbvedtaksstotte/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarbvedtaksstotte/internal/health/liveness
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi #https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-1-25600 # 1 vCPU, 25 GiB (25*1024 MB) RAM
        databases:
          - name: veilarbvedtaksstotte
            envVarPrefix: DB
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: AIA_BACKEND_TOKEN_SCOPE
      value: api://prod-gcp.paw.paw-arbeidssoker-besvarelse/.default
    - name: AIA_BACKEND_URL
      value: http://aia-backend.paw/aia-backend
    - name: DOKARKIV_TOKEN_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io
    - name: DOKDISTFORDELING_URL # bruker saf-scope
      value: https://dokdistfordeling.prod-fss-pub.nais.io
    - name: NORG2_URL
      value: http://norg2.org/norg2
    - name: PDL_TOKEN_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: POAO_TILGANG_TOKEN_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: PTO_PDFGEN_URL
      value: http://pto-pdfgen.obo
    - name: REGOPPSLAG_TOKEN_SCOPE
      value: api://prod-fss.teamdokumenthandtering.regoppslag/.default
    - name: REGOPPSLAG_URL
      value: https://regoppslag.prod-fss-pub.nais.io
    - name: SAF_TOKEN_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: SAF_URL
      value: https://saf.prod-fss-pub.nais.io
    - name: VEILARBARENA_TOKEN_SCOPE
      value: api://prod-fss.pto.veilarbarena/.default
    - name: VEILARBARENA_URL
      value: https://veilarbarena.prod-fss-pub.nais.io/veilarbarena
    - name: VEILARBOPPFOLGING_TOKEN_SCOPE
      value: api://prod-gcp.poao.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.poao/veilarboppfolging
    - name: VEILARBPERSON_TOKEN_SCOPE
      value: api://prod-gcp.obo.veilarbperson/.default
    - name: VEILARBPERSON_URL
      value: http://veilarbperson.obo/veilarbperson
    - name: VEILARBVEILEDER_TOKEN_SCOPE
      value: api://prod-gcp.obo.veilarbveileder/.default
    - name: VEILARBVEILEDER_URL
      value: http://veilarbveileder.obo/veilarbveileder
    # Topics
    - name: ENDRING_PA_OPPFOLGINGSBRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: ARENA_VEDTAK_TOPIC
      value: teamarenanais.aapen-arena-14avedtakiverksatt-v1-p
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
        - application: veilarbportefolje
          namespace: obo
          permissions:
            roles:
              - "siste-14a-vedtak"
        - application: veilarbpersonflate
          namespace: poao
        - application: beslutteroversikt
          namespace: obo
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
        - application: pto-admin
          namespace: pto
          cluster: prod-fss
        - application: amt-person-service
          namespace: amt
          permissions:
            roles:
              - "siste-14a-vedtak"
    outbound:
      rules:
        - application: aia-backend
          namespace: paw
        - application: paw-arbeidssoker-besvarelse
          namespace: paw
        - application: pto-pdfgen
          namespace: obo
        - application: veilarboppfolging
          namespace: poao
        - application: veilarbperson
          namespace: obo
        - application: veilarbveileder
          namespace: obo
        - application: poao-tilgang
          namespace: poao
        - application: norg2
          namespace: org
      external:
        - host: team-obo-unleash-api.nav.cloud.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: veilarbarena.prod-fss-pub.nais.io
        - host: saf.prod-fss-pub.nais.io
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: dokdistfordeling.prod-fss-pub.nais.io
        - host: regoppslag.prod-fss-pub.nais.io
  envFrom:
    - secret: veilarbvedtaksstotte-unleash-api-token
