package no.nav.veilarbvedtaksstotte.client.dokument

import com.fasterxml.jackson.annotation.JsonValue

enum class MalType(val navn: String) {
    STANDARD_INNSATS_SKAFFE_ARBEID_PROFILERING("STANDARD_INNSATS_SKAFFE_ARBEID_PROFILERING"),
    STANDARD_INNSATS_SKAFFE_ARBEID("STANDARD_INNSATS_SKAFFE_ARBEID"),
    STANDARD_INNSATS_BEHOLDE_ARBEID("STANDARD_INNSATS_BEHOLDE_ARBEID"),
    SITUASJONSBESTEMT_INNSATS_SKAFFE_ARBEID("SITUASJONSBESTEMT_INNSATS_SKAFFE_ARBEID"),
    SITUASJONSBESTEMT_INNSATS_BEHOLDE_ARBEID("SITUASJONSBESTEMT_INNSATS_BEHOLDE_ARBEID"),
    SPESIELT_TILPASSET_INNSATS_SKAFFE_ARBEID("SPESIELT_TILPASSET_INNSATS_SKAFFE_ARBEID"),
    SPESIELT_TILPASSET_INNSATS_BEHOLDE_ARBEID("SPESIELT_TILPASSET_INNSATS_BEHOLDE_ARBEID"),
    GRADERT_VARIG_TILPASSET_INNSATS_SKAFFE_ARBEID("GRADERT_VARIG_TILPASSET_INNSATS_SKAFFE_ARBEID"),
    GRADERT_VARIG_TILPASSET_INNSATS_BEHOLDE_ARBEID("GRADERT_VARIG_TILPASSET_INNSATS_BEHOLDE_ARBEID"),
    VARIG_TILPASSET_INNSATS("VARIG_TILPASSET_INNSATS");

    @JsonValue
    override fun toString(): String {
        return navn
    }
}
