name: Bygg og deploy til dev-gcp
on:
  workflow_dispatch:
env:
  PRINT_PAYLOAD: true
jobs:
  build-and-push:
    name: Build and push image
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build maven artifacts
        run: mvn -B package -D skipTests

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: obo

  deploy-dev:
    name: Deploy application to dev-gcp
    needs: build-and-push
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/application/application-config-dev.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
